### PR TITLE
Added support for ContentBlocks

### PR DESCRIPTION
**Pull request by jGleitz**
added `,itemCls: 'contentblocks_replacement'` to the definition of the `contentField` for msProduct and msCategory. This enables ContentBlocks support for minishop2. This change doesn't have any effects as long as someone does not have [ContentBlocks](https://www.modmore.com/extras/contentblocks/) installed and added `msProduct` and `msCategory` to `contentblocks.accepted_resource_types`. But if this is the case, minishop2 will now show ContentBlocks.

[Review on Reviewable](https://reviewable.io/reviews/bezumkin/minishop2/160)

### CODE REVIEW

**Comment by Ibochkarev** [comment]
@jGleitz Please fix conflicts. Thanks

**Comment by Ibochkarev** [comment]
@Mark-H Can you take a look, is this enough to add support for the add-on?

**Comment by Mark-H** [comment]
I don't have a minishop test shop to test, but yes this PR seems to cover the typical requirements for a custom resource type to work with ContentBlocks. https://docs.modmore.com/en/ContentBlocks/v1.x/Custom_Resources.html

**Comment by Ibochkarev** [comment]
> У меня нет минишопа для тестирования, но да, этот PR, кажется, покрывает типичные требования для пользовательского типа ресурса для работы с ContentBlocks. https://docs.modmore.com/en/ContentBlocks/v1.x/Custom_Resources.html

Thank

**Comment by Ibochkarev** [comment]
@jGleitz This PR cannot be accepted, so the addition has greatly changed the structure since 2014. If relevant. Please send a new PR for consideration.

Thank you for your contribution to the development.

**Pull request closed without merging**
